name: Appium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: '33.0.2'

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.android/cache
          ~/.android/avd
        key: ${{ runner.os }}-android-sdk
        restore-keys: |
          ${{ runner.os }}-android-sdk

    - name: Install Dependencies
      run: |
        sdkmanager --install 'system-images;android-33;default;arm64-v8a' 'emulator'
        sdkmanager --licenses

    - name: Create AVD
      run: |
        echo no | avdmanager create avd --force -n test --abi default/arm64-v8a --package 'system-images;android-33;default;arm64-v8a'
        echo "hw.cpu.ncore=2" >> ~/.android/avd/test.avd/config.ini

    # - name: Start Android emulator
    #   run: |
    #     nohup emulator -avd test -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -no-boot-anim -accel off > emulator.log 2>&1 &
    #     # Wait for emulator to start
    #     adb wait-for-device
    #     adb shell getprop sys.boot_completed

    - name: Start Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: arm64-v8a
        disable-linux-hw-accel: true
        emulator-options: '-no-window -no-audio -gpu swiftshader_indirect -no-snapshot -no-boot-anim -verbose'
        emulator-boot-timeout: 15m
        script: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb shell input keyevent 82

    # - name: Create and start Android emulator
    #   run: |

    #     echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
        
    #     echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

    #     $ANDROID_HOME/emulator/emulator-headless @test -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -no-boot-anim &

    #     adb wait-for-device
    #     adb shell settings put global window_animation_scale 0
    #     adb shell settings put global transition_animation_scale 0
    #     adb shell settings put global animator_duration_scale 0
    #     adb shell input keyevent 82

    - name: Set Up .NET core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'    

    - name: Install and Run Appium Server
      run: |
        npm install -g appium@2.0.0-beta.63
        appium driver install uiautomator2
        nohup appium &

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
  
    - name: Run Tests
      run: dotnet test --verbosity normal
