name: Appium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Switching to macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'  

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: '33.0.2'

    - name: Install Android SDK components
      run: |
        sdkmanager --install 'system-images;android-33;google_apis;x86_64' 'emulator'
        sdkmanager --licenses

    - name: Create AVD
      run: |
        echo no | avdmanager create avd --force -n test -k 'system-images;android-33;google_apis;x86_64' --device 'pixel'
        echo "hw.cpu.ncore=2" >> ~/.android/avd/test.avd/config.ini
        echo "hw.gpu.mode=auto" >> ~/.android/avd/test.avd/config.ini
        echo "hw.ramSize=2048" >> ~/.android/avd/test.avd/config.ini

    - name: Start Android emulator
      run: |
        nohup emulator -avd test -no-snapshot -no-boot-anim -accel on -gpu on > /dev/null 2>&1 &
        adb wait-for-device
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0
        adb shell input keyevent 82

    - name: Set Up .NET core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'    

    - name: Install and Run Appium Server
      run: |
        npm install -g appium@2.0.0-beta.63
        appium driver install uiautomator2
        nohup appium > /dev/null 2>&1 &

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
  
    - name: Run Tests
      run: dotnet test --verbosity normal

    - name: Clean Up Emulator
      if: always()
      run: adb -s emulator-5554 emu kill
